import assert from 'node:assert/strict';
import {readFile,stat,writeFile} from 'node:fs/promises';
const pages=JSON.parse(await readFile('.local/pages.json','utf8'));
const titles=new Set(),descriptions=new Set();let links=0,schemas=0;const docs=new Map();
for(const p of pages){const file=p.route==='/'?'index.html':p.route.slice(1)+'index.html';const html=await readFile(file,'utf8');docs.set(p.route,html);assert.equal((html.match(/<h1[ >]/g)||[]).length,1,`${file}: one H1`);assert(!/noindex|localhost|TODO|placeholder testimonial/i.test(html),`${file}: production readiness`);assert(!titles.has(p.title),`${file}: duplicate title`);titles.add(p.title);assert(!descriptions.has(p.description),`${file}: duplicate description`);descriptions.add(p.description);assert(html.includes(`rel="canonical" href="https://tech-stuff.tech${p.route}"`),`${file}: canonical`);for(const s of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)){const data=JSON.parse(s[1]);assert.equal(data['@context'],'https://schema.org');const business=data['@graph'].find(x=>x['@type']==='LocalBusiness');assert.equal(business.telephone,'+15036622669');assert(!business.address,'No private address');assert.equal(business.openingHoursSpecification[0].closes,'21:00');assert(!business.aggregateRating,'No invented ratings');schemas++;}for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){const url=m[1];if(!url.startsWith('/'))continue;const [path,hash]=url.split('#');if(path==='/'||path.endsWith('/')){assert(pages.some(p=>p.route===path),`${file}: missing page ${path}`);if(hash){const dest=await readFile(path==='/'?'index.html':path.slice(1)+'index.html','utf8');assert(dest.includes(`id="${hash}"`),`${file}: broken anchor ${url}`)}}else assert((await stat(path.slice(1))).isFile(),`${file}: missing asset ${path}`);links++;}}
const sitemap=await readFile('sitemap.xml','utf8');assert.equal((sitemap.match(/<loc>/g)||[]).length,pages.length);for(const p of pages)assert(sitemap.includes('https://tech-stuff.tech'+p.route));assert(!(await readFile('robots.txt','utf8')).includes('Disallow: /\n'));assert((await readFile('404.html','utf8')).includes('noindex,follow'));
const base=process.argv[2]||'http://localhost:4321';const http=[];
for(const p of pages){const res=await fetch(base+p.route);assert.equal(res.status,200,`${p.route}: HTTP status`);const html=await res.text();assert(html.includes(`<title>${p.title.replaceAll('&','&amp;')}</title>`),`${p.route}: deployed build mismatch`);http.push({route:p.route,status:res.status,bytes:Buffer.byteLength(html)});}
const missing=await fetch(base+'/this-page-does-not-exist-20260909/');assert.equal(missing.status,404,'Unknown path must return 404');assert((await missing.text()).includes('That page isn’t here.'),'Custom 404 page');
const result={checkedAt:new Date().toISOString(),base,pages:pages.length,internalLinksAndAssets:links,jsonLdDocuments:schemas,uniqueTitles:titles.size,uniqueDescriptions:descriptions.size,http};await writeFile('.local/validation-'+(base.includes('localhost')?'local':'production')+'.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
